# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_for', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=50)),
                ('exp_date', models.DateField()),
                ('exp_rep', models.IntegerField(default=0)),
                ('exp_loan', models.BooleanField(default=False)),
                ('exp_loan_to', models.CharField(max_length=50)),
                ('cat_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=50)),
                ('goal_amount', models.IntegerField(default=0)),
                ('goal_deadline', models.DateField()),
                ('amount_now', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_name', models.CharField(max_length=50)),
                ('inc_date', models.DateField()),
                ('inc_rep', models.IntegerField(default=0)),
                ('inc_debt', models.BooleanField(default=False)),
                ('inc_debt_to', models.CharField(max_length=50)),
                ('cat_inc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('pass_word', models.CharField(max_length=100)),
                ('currency', models.IntegerField(default=0)),
                ('decimal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wal_name', models.CharField(max_length=50)),
                ('user_wal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Users')),
            ],
        ),
        migrations.AddField(
            model_name='incomes',
            name='user_inc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Users'),
        ),
        migrations.AddField(
            model_name='incomes',
            name='wal_inc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Wallets'),
        ),
        migrations.AddField(
            model_name='goals',
            name='user_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='wal_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Wallets'),
        ),
        migrations.AddField(
            model_name='categories',
            name='user_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Users'),
        ),
    ]
