# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_wallets_wal_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_loan_to',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='inc_debt_to',
            field=models.CharField(default='', max_length=50),
        ),
    ]
