# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20170105_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_loan_to',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='inc_debt_to',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
