# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20170105_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='inc_amount',
            field=models.FloatField(default=1),
        ),
    ]
