# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20170105_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='currency',
            field=models.CharField(default='\u20ac', max_length=20),
        ),
    ]
