# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20170111_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pass_word',
        ),
    ]
